### PR TITLE
refactor: Use unions to describe DOM

### PR DESCRIPTION
**Pull request by fb55**
As proposed by @43081j

### CODE REVIEW

**Comment by fb55** [comment]
@43081j I'd love to get your eyes on this prior to merging. The downside I saw was compatibility of the htmlparser2 adapter with the `domhandler` types.

**Comment by 43081j** [comment]
couple of questions/things:

* a tree adapter could technically have different child types to another tree adapter, but doesn't currently and never has. so the way you've done it is fine but if we wanted to, we could account for it by reversing it: have a `T['childNode']` which is a union inside each adapter (so each adapter has to specify what it is)
* you could still have some kind of base interface for the `childNodes` etc, common properties but they'd never be consumed. they'd just exist to make our interfaces smaller, up to you

can you show me where the domhandler problem exists? an example of it somewhere?

**Comment by fb55** [comment]
Thanks for your reply @43081j, keeping `node`, `parentNode` and `childNode` as separate entries on the type map makes sense. I've updated things, let me know what you think.

**Comment by 43081j** [comment]
No worries I'll have another read. 

I actually had a chat with a few people in the typescript discord about this. Our type map currently results in everything ultimately being unknown. So you can pass a document to a function consuming an element for example. 

The only way to solve this is to have a type parameter for each type rather than a map. Then hope the compiler can infer it in most cases. I've been working on it on a branch so I'll try publish it soon to explain it a bit better. That may affect this pr though

**Pull request merged**
